### ISSUE TITLE
Tier 5 Todo list

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2393]
Here is the todo list for tier 5 (its not complete)

- [ ] create grafics for tier 5 settlers home building
- [ ] add grafics for tier 5 settler units/ first this need to be fixed: https://github.com/unknown-horizons/unknown-horizons/issues/2388
- [ ] create work buildings for tier 5
- [ ] update buildmenu (for tier 5)
- [ ] add new ships (for tier 5)
- [ ] add new productions lines
