### ISSUE TITLE
Review some closed PR´s

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2577]
Review some closed PR´s

* [ ] #2571 Dynamic game speed

* [ ] #2570 Message panel

* [ ] #2569 Incr

* [ ] #2568 Loaders

* [ ] #2566 Datacollect

* [ ] #2563 Simulation cleanup

* [ ] #2560 Wide tooltips

* [ ] #2460 [DONT MERGE] Needs big review - Multiplayer improvement

* [ ] #2459 Menu game separation

* [ ] #2575 Attack via minimap

**Comment by jakoch** [comment]
Why do you need to review closed PRs?
Do you want to extract features from non-merged PRs?

**Comment by MasterofJOKers** [comment]
The branches backing these PRs are really old. They need to be updated to have any chance of getting merged. That's why the PRs are closed. He wants to figure out, if we still want any of the features implemented in these branches. E.g. #2459 is probably a good thing when we want to split off the AI at some point in time, but does not apply to the current master at all.

**Comment by jakoch** [comment]
Ok, that makes sense. So, it's feature extraction from branches. Thanks for explaining!
