### ISSUE TITLE
Create Tier 2 Buildings (Pioneers)

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#598]
This serves as a ticket which is blocked by all graphics of buildings we currently lack or would like to be updated. 

Only graphics which are planned to get available in tier 2 reside here.

Browse through the list. Possible buildings are not checked.
Those are the tickets about the specific gfx:

- [x] hunter: #234
- [x] school: #458
- [x] sugar field: #465
- [x] distillery: #466
- [x] brickyard: #519
- [x] weaver: #472 #603
- [x] boat builder: #474
- [x] field for farm #600
- [x] brewery #604
- [x] distillery #606
- [x] charcoal burning #607
- [x] wooden church #609
- [x] wooden signal fire #610
- [x] fire brigade #611
- [x] wooden main square #612
- [x] wooden pier #613 #951 #1098
- [x] storage hut #614 
- [x] gravel path #615

**Comment by stubb** [comment]
Everything is done.
